queue.h
test/queue.C
test/run_q_test.sh

Trivial Q implementation with push/pop functionality with simple tests.

Add simple queue implementation

---

convcore.C
convcore.h
converse.h
examples/startup/startup.C
scheduler.C

Implementation for exiting the scheduler. I add the flag in the State struct and use that to exit the scheduler (seems to work for startup.C).

exit scheduler implementation

---

convcore.C
convcore.h
examples/ping_ack/Makefile
examples/ping_ack/ping.c
examples/startup/Makefile
examples/startup/startup.C
scheduler.C

This is my first attempt at a nodequeue. I'm reusing the existing (lock-based) MPSCQueue class since it seems to adequately control access to a shared queue for all threads on the node.

initial nodequeue implementation

---

.gitignore
CMakeLists.txt
cmake_modules/AddReconverse.cmake
convcore.C
examples/CMakeLists.txt
examples/broadcast/CMakeLists.txt
examples/conds/CMakeLists.txt
examples/orig-converse/pingpong/CMakeLists.txt
examples/ping_ack/CMakeLists.txt
examples/ring/CMakeLists.txt
examples/startup/CMakeLists.txt
test/CMakeLists.txt

Usage:
```
cd reconverse
mkdir build
cd build
cmake ..
make
```
flyby: add a `.gitignore`.

Add basic cmake support

---

convcore.C
converse.h
examples/broadcast/CMakeLists.txt
examples/broadcast/broadcast.C
scheduler.C

Implemented the following handler functionality:
- CmiGetHandler
- CmiGetHandlerFunction
- CmiHandleMessage

Handler API additions

---

convcore.C
converse.h
examples/broadcast/CMakeLists.txt
examples/broadcast/broadcast.C
scheduler.C

Reverts charmplusplus/reconverse#13

Revert "Handler API additions" to fix CI issues

---

CMakeLists.txt
src/CMakeLists.txt
src/convcore.C
src/converse_internal.h
src/cpuaffinity.C

Adding code from converse to use hwloc to set cpu affinity. For now, it assumes for one process per node.

Add cpu affinity using hwloc

---

examples/CMakeLists.txt
examples/within-node-bcast/CMakeLists.txt
examples/within-node-bcast/Makefile
examples/within-node-bcast/wnbcast.C
include/converse.h
src/convcore.C

With simple example and two tests (single node vs two nodes).

Adding CmiWithinNodeBroadcast

---

examples/broadcast/broadcast.C
src/convcore.C

Small improvements including 
- add assertion for pushPE
- reclaim resources during finalization
- fix broadcast print

add assertion for pushPE; reclaim resources during finalization

---

examples/ping_ack/ping.C
src/convcore.C
src/converse_internal.h

Fix CmiAbort to error out correctly

---

include/converse.h
src/convcore.cpp
src/threads.cpp

Thread listener

---

test/CMakeLists.txt
test/queue.cpp

PR #50 accidentally deleted the queue test. This re-enables

Re-enable the queue test

---

include/converse.h
src/collectives.cpp
src/convcore.cpp
src/converse_internal.h
src/queue.h
src/scheduler.cpp

We need to be able to run CsdSchedulePoll (which returns if the queues are empty) so I've added that function. This also moves NcpyOperationInfo down to reconverse.

schedule poll function and others

---

include/converse.h
src/convcore.cpp
src/converse_internal.h

I've added message reference counting, and there are also methods and variables i've added here, such as macros used in ckrdma. Once this is merged, libck will compile successfully.

ref counting and other methods

---

examples/rdma_pingpong/pingpong.cpp

Updated the RDMA pingpong example to only use one way acks.

Modified example

---

CMakeLists.txt
src/collectives.cpp

Need to merge to fix broadcasts called early on in Charm's initialization.

fix broadcasts

---

include/converse.h
src/CMakeLists.txt
src/convcore.cpp

To fix without `--with-production` build

Add traceInit registration

---

CMakeLists.txt
README.md
cmake_modules/FindHWLOC.cmake
src/convcore.cpp
src/converse_config.h.in
src/cpuaffinity.cpp

Always try finding hwloc and enable affinity if hwloc is found.

cmake: improve ENABLE_CPU_AFFINITY logic

---

src/convcore.cpp

We need this to support tracing in Charm++.

add back Cmi_argvcopy

---

CMakeLists.txt
src/converse_config.h.in

Turn on CMK_CPV_IS_SMP for Charm++

---

include/converse.h
src/convcore.cpp
src/cpuaffinity.cpp

These changes include modifications to converse.h so that C files can include converse.h. It's possible that those changes may look weird/don't make sense, so I hope someone who knows how to write modules for both C and C++ can tell me if I did this correctly

Fixes to allow changa to run on reconverse
